### ISSUE TITLE
EntitySubscriberInterface like TypeORM

### ISSUE THREAD

**Issue by carmas123** [dario1985/nestjs-mikro-orm#9]
Hi, I want to migrate my app from TypeORM to MikroORM. Now I've a problem with event listening.
In TypeORM I've a EntitySubscriberInterface injectable by @Subscriber() that hook all events afterUpdate, beforeUpdate or other into an external handler and not directly into the entity. This is very useful to manage some events from external.

There is an alternative into MikroORM?

**Comment by B4nan** [comment]
Closing as implemented in v4
